package GUI;

import Function.FuncAutor;
import Function.FuncLeitor;
import Function.FuncLivro;


public class Menu extends javax.swing.JFrame {
    

    //alterar para o diretório desejado...
    String dir="C:\\BANCO";
    
    
    public Menu() {
        initComponents();


    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAdd = new javax.swing.JButton();
        btProcurarAutor = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        lbAutor = new javax.swing.JLabel();
        lbAutor1 = new javax.swing.JLabel();
        lbAutor2 = new javax.swing.JLabel();
        lbAutor3 = new javax.swing.JLabel();
        lbAutor5 = new javax.swing.JLabel();
        lbAutor6 = new javax.swing.JLabel();
        txtNomeAutor = new javax.swing.JTextField();
        txtNomeLeitor = new javax.swing.JTextField();
        txtTituloLivro = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btAddLeitor = new javax.swing.JButton();
        btProcurarLeitor = new javax.swing.JButton();
        btAlterarLeitor = new javax.swing.JButton();
        btRemoverLeitor = new javax.swing.JButton();
        btLimparLeitor = new javax.swing.JButton();
        txtCodAutor = new javax.swing.JFormattedTextField();
        txtCodLeitor = new javax.swing.JFormattedTextField();
        txtCodLivro = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btLimparLivro = new javax.swing.JButton();
        btAddLivro = new javax.swing.JButton();
        btProcurarLivro = new javax.swing.JButton();
        btAlterarLivro = new javax.swing.JButton();
        btRemoverLivro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        btAdd.setText("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btProcurarAutor.setText("Procurar");
        btProcurarAutor.setPreferredSize(new java.awt.Dimension(77, 23));
        btProcurarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarAutorActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.setPreferredSize(new java.awt.Dimension(77, 23));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.setPreferredSize(new java.awt.Dimension(77, 23));
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        lbAutor.setText("Nome Autor");

        lbAutor1.setText("Código Autor");

        lbAutor2.setText("Código Leitor");

        lbAutor3.setText("Nome Leitor");

        lbAutor5.setText("ISBN Livro");

        lbAutor6.setText("Título  Livro");

        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(77, 23));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btAddLeitor.setText("Adicionar");
        btAddLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLeitorActionPerformed(evt);
            }
        });

        btProcurarLeitor.setText("Procurar");
        btProcurarLeitor.setPreferredSize(new java.awt.Dimension(77, 23));
        btProcurarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarLeitorActionPerformed(evt);
            }
        });

        btAlterarLeitor.setText("Alterar");
        btAlterarLeitor.setPreferredSize(new java.awt.Dimension(77, 23));
        btAlterarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarLeitorActionPerformed(evt);
            }
        });

        btRemoverLeitor.setText("Remover");
        btRemoverLeitor.setPreferredSize(new java.awt.Dimension(77, 23));
        btRemoverLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverLeitorActionPerformed(evt);
            }
        });

        btLimparLeitor.setText("Limpar");
        btLimparLeitor.setPreferredSize(new java.awt.Dimension(77, 23));
        btLimparLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparLeitorActionPerformed(evt);
            }
        });

        try {
            txtCodAutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCodLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCodLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-####-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCodLivro.setToolTipText("");

        jLabel1.setText("Ex. A001");

        jLabel2.setText("Ex. 001L");

        jLabel3.setText("Ex. XXX-XX-XXXX-XXX-X");

        btLimparLivro.setText("Limpar");
        btLimparLivro.setPreferredSize(new java.awt.Dimension(77, 23));
        btLimparLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparLivroActionPerformed(evt);
            }
        });

        btAddLivro.setText("Adicionar");
        btAddLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLivroActionPerformed(evt);
            }
        });

        btProcurarLivro.setText("Procurar");
        btProcurarLivro.setPreferredSize(new java.awt.Dimension(77, 23));
        btProcurarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarLivroActionPerformed(evt);
            }
        });

        btAlterarLivro.setText("Alterar");
        btAlterarLivro.setPreferredSize(new java.awt.Dimension(77, 23));
        btAlterarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarLivroActionPerformed(evt);
            }
        });

        btRemoverLivro.setText("Remover");
        btRemoverLivro.setPreferredSize(new java.awt.Dimension(77, 23));
        btRemoverLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btProcurarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoverLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAutor2)
                            .addComponent(lbAutor3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddLeitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btProcurarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoverLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAdd)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAutor1)
                            .addComponent(lbAutor)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAutor5)
                            .addComponent(lbAutor6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btProcurarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(btSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addComponent(txtNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btProcurarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(15, 15, 15)
                        .addComponent(txtNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAutor1)
                        .addGap(15, 15, 15)
                        .addComponent(lbAutor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddLeitor)
                    .addComponent(btProcurarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemoverLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimparLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor2)
                    .addComponent(txtCodLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAutor3)
                    .addComponent(txtNomeLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddLivro)
                    .addComponent(btProcurarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemoverLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimparLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor5)
                    .addComponent(txtCodLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor6)
                    .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed

        FuncAutor funcAutor = new FuncAutor(dir);
        String codAutor = txtCodAutor.getText();
        String nomeAutor = txtNomeAutor.getText();
        funcAutor.addAutor(codAutor, nomeAutor); 

    }//GEN-LAST:event_btAddActionPerformed

    private void btProcurarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarAutorActionPerformed

        FuncAutor funcAutor = new FuncAutor(dir);
        String codAutor = txtCodAutor.getText();
        funcAutor.findAutor(codAutor);
        dispose();
    }//GEN-LAST:event_btProcurarAutorActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
       // SelecionarDiretorio select = new SelecionarDiretorio();
       // String dir = select.getTxtDiretorio();
        FuncAutor funcAutor = new FuncAutor(dir);
        String codAutor = txtCodAutor.getText();
        funcAutor.alterarAutor(codAutor);
        dispose();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        //SelecionarDiretorio select = new SelecionarDiretorio();
       // String dir = select.getTxtDiretorio();
        FuncAutor funcAutor = new FuncAutor(dir);
        String codAutor = txtCodAutor.getText();
        funcAutor.removerAutor(codAutor);
        dispose();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        txtCodAutor.setText("");            
        txtNomeAutor.setText("");
        
        
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAddLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLeitorActionPerformed
        // TODO add your handling code here:
        FuncLeitor funcLeitor = new FuncLeitor(dir);
        String codLeitor = txtCodLeitor.getText();
        String nomeLeitor = txtNomeLeitor.getText();
        funcLeitor.addLeitor(codLeitor, nomeLeitor); 
        dispose();
    }//GEN-LAST:event_btAddLeitorActionPerformed

    private void btProcurarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarLeitorActionPerformed
        // TODO add your handling code here:
        FuncLeitor funcLeitor = new FuncLeitor(dir);
        String codLeitor = txtCodLeitor.getText();
        funcLeitor.findLeitor(codLeitor);
        dispose();
    }//GEN-LAST:event_btProcurarLeitorActionPerformed

    private void btAlterarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarLeitorActionPerformed
        // TODO add your handling code here:
        FuncLeitor funcLeitor = new FuncLeitor(dir);
        String codLeitor = txtCodLeitor.getText();
        funcLeitor.alterarLeitor(codLeitor);
        dispose();
    }//GEN-LAST:event_btAlterarLeitorActionPerformed

    private void btRemoverLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverLeitorActionPerformed
        // TODO add your handling code here:
        FuncLeitor funcLeitor = new FuncLeitor(dir);
        String codLeitor = txtCodLeitor.getText();
        funcLeitor.removerLeitor(codLeitor);
        dispose();
    }//GEN-LAST:event_btRemoverLeitorActionPerformed

    private void btLimparLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparLeitorActionPerformed
        // TODO add your handling code here:
        txtCodLeitor.setText("");
        txtNomeLeitor.setText("");
        
    }//GEN-LAST:event_btLimparLeitorActionPerformed

    private void btLimparLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparLivroActionPerformed
        // TODO add your handling code here:
        txtCodLivro.setText("");
        txtTituloLivro.setText("");
    }//GEN-LAST:event_btLimparLivroActionPerformed

    private void btAddLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLivroActionPerformed
        // TODO add your handling code here:
        FuncLivro funcLivro = new FuncLivro(dir);
        String codLivro = txtCodLivro.getText();
        String tituloLivro = txtTituloLivro.getText();
        funcLivro.addLivro(codLivro, tituloLivro);
        dispose();
    }//GEN-LAST:event_btAddLivroActionPerformed

    private void btProcurarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarLivroActionPerformed
        FuncLivro funcLivro = new FuncLivro(dir);
        String codLivro = txtCodLivro.getText();

        funcLivro.findLivro(codLivro);
        dispose();
    }//GEN-LAST:event_btProcurarLivroActionPerformed

    private void btAlterarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarLivroActionPerformed
        // TODO add your handling code here:
        FuncLivro funcLivro = new FuncLivro(dir);
        String codLivro = txtCodLivro.getText();

        funcLivro.alterarLivro(codLivro);
        dispose();
    }//GEN-LAST:event_btAlterarLivroActionPerformed

    private void btRemoverLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverLivroActionPerformed
        FuncLivro funcLivro = new FuncLivro(dir);
        String codLivro = txtCodLivro.getText();

        funcLivro.removerLivro(codLivro);
        dispose();
    }//GEN-LAST:event_btRemoverLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAddLeitor;
    private javax.swing.JButton btAddLivro;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAlterarLeitor;
    private javax.swing.JButton btAlterarLivro;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLimparLeitor;
    private javax.swing.JButton btLimparLivro;
    private javax.swing.JButton btProcurarAutor;
    private javax.swing.JButton btProcurarLeitor;
    private javax.swing.JButton btProcurarLivro;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btRemoverLeitor;
    private javax.swing.JButton btRemoverLivro;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbAutor1;
    private javax.swing.JLabel lbAutor2;
    private javax.swing.JLabel lbAutor3;
    private javax.swing.JLabel lbAutor5;
    private javax.swing.JLabel lbAutor6;
    private javax.swing.JFormattedTextField txtCodAutor;
    private javax.swing.JFormattedTextField txtCodLeitor;
    private javax.swing.JFormattedTextField txtCodLivro;
    private javax.swing.JTextField txtNomeAutor;
    private javax.swing.JTextField txtNomeLeitor;
    private javax.swing.JTextField txtTituloLivro;
    // End of variables declaration//GEN-END:variables

    public void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
